export const TORUS__CONNECT = "TORUS__CONNECT";
export const TORUS__CONNECT_SUCCEEDED = "TORUS__CONNECT_SUCCEEDED";
export const TORUS__CONNECT_FAILED = "TORUS__CONNECT_FAILED";

export const TORUS__DISCONNECTED = "TORUS__DISCONNECTED";

export const TORUS__GET_PK = "TORUS__GET_PK";
export const TORUS__GET_PK_SUCCEEDED = "TORUS__GET_PK_SUCCEEDED";
export const TORUS__GET_PK_FAILED = "TORUS__GET_PK_FAILED";
