export const METAMASK__CONNECT = "METAMASK__CONNECT";
export const METAMASK__CONNECT_SUCCEEDED = "METAMASK__CONNECT_SUCCEEDED";
export const METAMASK__CONNECT_FAILED = "METAMASK__CONNECT_FAILED";

export const METAMASK__DISCONNECTED = "METAMASK__DISCONNECTED";

export const METAMASK__GET_PK = "METAMASK__GET_PK";
export const METAMASK__GET_PK_SUCCEEDED = "METAMASK__GET_PK_SUCCEEDED";
export const METAMASK__GET_PK_FAILED = "METAMASK__GET_PK_FAILED";
