export const WALLETCONNECT_CONNECT = "WALLETCONNECT_CONNECT";
export const WALLETCONNECT_CONNECT_SUCCEEDED = "WALLETCONNECT_CONNECT_SUCCEEDED";
export const WALLETCONNECT_CONNECT_FAILED = "WALLETCONNECT_CONNECT_FAILED";

export const WALLETCONNECT_DISCONNECTED = "WALLETCONNECT_DISCONNECTED";
