export const THREEBOX_CONNECT = "THREEBOX_CONNECT";
export const THREEBOX_CONNECT_SUCCEEDED = "THREEBOX_CONNECT_SUCCEEDED";
export const THREEBOX_CONNECT_FAILED = "THREEBOX_CONNECT_FAILED";

export const THREEBOX_LIST_SPACES = "THREEBOX_LIST_SPACES";
export const THREEBOX_LIST_SPACES_SUCCEEDED = "THREEBOX_LIST_SPACES_SUCCEEDED";
export const THREEBOX_LIST_SPACES_FAILED = "THREEBOX_LIST_SPACES_FAILED";

export const THREEBOX_GET_SPACE = "THREEBOX_GET_SPACE";
export const THREEBOX_GET_SPACE_SUCCEEDED = "THREEBOX_GET_SPACE_SUCCEEDED";
export const THREEBOX_GET_SPACE_FAILED = "THREEBOX_GET_SPACE_FAILED";

export const THREEBOX_GET_THREAD = "THREEBOX_GET_THREAD";
export const THREEBOX_GET_THREAD_SUCCEEDED = "THREEBOX_GET_THREAD_SUCCEEDED";
export const THREEBOX_GET_THREAD_FAILED = "THREEBOX_GET_THREAD_FAILED";

export const THREEBOX_GET_THREAD_BY_ADDRESS = "THREEBOX_GET_THREAD_BY_ADDRESS";
export const THREEBOX_GET_THREAD_BY_ADDRESS_SUCCEEDED = "THREEBOX_GET_THREAD_BY_ADDRESS_SUCCEEDED";
export const THREEBOX_GET_THREAD_BY_ADDRESS_FAILED = "THREEBOX_GET_THREAD_BY_ADDRESS_FAILED";

export const THREEBOX_DISCONNECTED = "THREEBOX_DISCONNECTED";
