export const THREEBOX_CONNECT = "THREEBOX_CONNECT";
export const THREEBOX_CONNECT_SUCCEEDED = "THREEBOX_CONNECT_SUCCEEDED";
export const THREEBOX_CONNECT_FAILED = "THREEBOX_CONNECT_FAILED";

export const THREEBOX_DISCONNECTED = "THREEBOX_DISCONNECTED";
